### ISSUE TITLE
BUILD FAILED: Could not find flutter:flutter:0.0.7

### ISSUE THREAD

**Issue by OlJohnny** [emiliodallatorre/flutter_rtmp_broadcaster#21]
When building an app with this plugin in release mode the following error gets thrown:

<pre>Execution failed for task ':app:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not find flutter:flutter:0.0.7.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/flutter/flutter/0.0.7/flutter-0.0.7.pom
       - https://repo.maven.apache.org/maven2/flutter/flutter/0.0.7/flutter-0.0.7.pom
       - https://storage.googleapis.com/download.flutter.io/flutter/flutter/0.0.7/flutter-0.0.7.pom
       - https://jcenter.bintray.com/flutter/flutter/0.0.7/flutter-0.0.7.pom
       - https://jitpack.io/flutter/flutter/0.0.7/flutter-0.0.7.pom
     Required by:
         project :app > project :rtmp_broadcaster</pre>

This is due to the weird flutter dependency in <code>android/build.gradle</code>

If anybody has any idea, why this weird dependency exists, let me know

**Comment by gafsel** [comment]
Same here, does anyone has any fix for this?

**Comment by OlJohnny** [comment]
I have made a branch removing the offending dependency: https://github.com/OlJohnny/flutter_rtmp_broadcaster

to use the branch in your app change the dependency in the <code>pubspec.yaml</code> of your app
from:
<pre>  rtmp_broadcaster: ^2.2.4</pre>
to:
<pre>  rtmp_broadcaster:
    git: https://github.com/OlJohnny/flutter_rtmp_broadcaster.git</pre>

after that run <code>flutter pub get</code> again to update the local packages

**Comment by RutulTrivedi** [comment]
I think there is an issue in declaring dependency. You can make changes in **build.gradle** file. Your **rtmp_broadcaster** module is referencing another module. Add/Update the flutter version there.
Still is there is an issue, clean and rebuild the project in the following way,
`./gradlew clean`
`./gradlew rebuild`

**Comment by meibadkhan** [comment]
how I can mute or unMute voice, when I click on enable or disable it cancel the streaming and also if I already set audio to false then it is not working and still voice is recording.....?
Any Solutions?

**Comment by OlJohnny** [comment]
please don't use this issue for other problems, open a new issue instead with logs, environment etc.

the "fix" for this issue is [here](https://github.com/emiliodallatorre/flutter_rtmp_broadcaster/issues/21#issuecomment-2299124501)

**Comment by emiliodallatorre** [comment]
Sorry guys, I didn't see this issue. I resolved in my last version; thanks @OlJohnny for noticing!

Best!
